### ISSUE TITLE
Installation error (Failed building wheel for zigzag)

### ISSUE THREAD

**Issue by claltan** [joshyattridge/smartmoneyconcepts#3]
Thank you very much for your effort on this. It was a highly anticipated package for me. I am trying to install via pip however end up with an error:

ERROR: Failed building wheel for zigzag
Failed to build zigzag
ERROR: Could not build wheels for zigzag, which is required to install pyproject.toml-based projects

Do you have any suggestions?
Thank you in advance

**Comment by rafalsza** [comment]
https://github.com/jbn/ZigZag/issues/32

**Comment by claltan** [comment]
@rafalsza You are the best!
