### ISSUE TITLE
Add smc indicator to freqtrade

### ISSUE THREAD

**Issue by bamboochainlab** [joshyattridge/smartmoneyconcepts#8]
Please add smc indicator to freqtrade

**Comment by joshyattridge** [comment]
Hello @bamboochainlab,

You are welcome to use the smartmoneyconcepts package within Freqtrade.
But it is down to you to implement this and make smartmoneyconcepts work for your project.

I hope this answers your questions

**Comment by james-lukensow-cbm** [comment]
I'm actually trying to add it right now, as an indicator. I can get the beginning of the order block to print, but it doesn't extend past the first occurrence, until a mitigation is found. I'm guessing, I have to loop through all the found FVG's, and add the values to the dataframe in Freqtrade, until a mitigation is found?
